export {
  BRIDGE_VERSION,
  DEFAULT_EXPOSED_MODELS,
  DEFAULT_OLLAMA_PORT,
  FALLBACK_OLLAMA_PORT,
  createOllamaServer,
  serveOllamaBridge,
  type OllamaServerConfig,
  type ServeHandle,
} from './server.ts'

export {
  DEFAULT_POOL_IDLE_TTL_MS,
  DEFAULT_POOL_MAX,
  SessionPool,
  hashHistoryPrefix,
  type PooledSession,
  type SessionPoolOptions,
} from './session-pool.ts'

export {
  OLLAMA_CAPABILITIES,
  buildDoneFrame,
  buildPromptFromOllamaMessages,
  buildShowResponse,
  buildTagsResponse,
  buildTextDeltaFrame,
  buildThinkingDeltaFrame,
  buildToolCallFrame,
  mapDoneReason,
  ollamaMessagesToHistory,
  type FrameDurations,
} from './transform.ts'

export type {
  OllamaChatFrame,
  OllamaChatRequest,
  OllamaErrorResponse,
  OllamaMessage,
  OllamaModelDetails,
  OllamaModelTag,
  OllamaRole,
  OllamaShowRequest,
  OllamaShowResponse,
  OllamaTagsResponse,
  OllamaToolCall,
  OllamaToolDefinition,
  OllamaVersionResponse,
} from './types.ts'

export {
  StreamingChunkConverter,
  attachmentsFromHistory,
  buildNonStreamingResponse,
  buildPromptFromOpenAIMessages,
  extractAssistantContent,
  extractUsage,
  mapStopReason,
  openAIMessagesToHistory,
  type NonStreamingExtraction,
  type OpenAIChatCompletionChoice,
  type OpenAIChatCompletionChunk,
  type OpenAIChatCompletionRequest,
  type OpenAIChatCompletionResponse,
  type OpenAIChatCompletionStreamChoice,
  type OpenAIChatCompletionStreamDelta,
  type OpenAIChatCompletionUsage,
  type OpenAIContentPart,
  type OpenAIFinishReason,
  type OpenAIMessage,
  type OpenAIMessageRole,
  type OpenAIModelEntry,
  type OpenAIModelsResponse,
  type OpenAIToolCall,
  type OpenAIToolDefinition,
} from './openai-compat.ts'
